spring.application.name=Eureka
server.port=8762

eureka.client.register-with-eureka=false
eureka.client.allow-redirects=false
eureka.server.enable-self-preservation=false
eureka.client.fetch-registry=false
