spring.application.name=UserGRA

server.port=8050
jwt.secret=8a$3JdK!zPqT&vXb@9LwY#RmN*CtZ7Fg5QKdVpXr8a$3JdK!zPqT&vXb@9LwY#RmN*CtZ7Fg5QKdVpXr
spring.datasource.url=jdbc:oracle:thin:@192.168.50.1:1521/XEPDB1
spring.datasource.username=sarah
spring.datasource.password=gra123

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
# Activation de l?enregistrement dans Eureka
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=DEBUG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE 
spring.datasource.hikari.connection-timeout=30000
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG
logging.level.org.springframework.transaction=TRACE
spring.datasource.hikari.pool-name=HikariPool-1
spring.datasource.hikari.leak-detection-threshold=5000
logging.level.com.zaxxer.hikari=DEBUG
spring.datasource.hikari.maximum-pool-size=20
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zayatisarah@gmail.com
spring.mail.password=nbpw pvls ivbv mwgu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false


