spring.application.name=UserGRA

server.port=8050
jwt.secret=123456789
spring.datasource.url=jdbc:oracle:thin:@192.168.50.1:1521:XE?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=SYSTEM
spring.datasource.password=SYSTEM
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
# Activation de l?enregistrement dans Eureka
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=DEBUG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG
logging.level.org.springframework.transaction=TRACE

