# Nom du microservice
spring.application.name=CLIENT
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
# Port
server.port=8051

# Datasource Oracle
spring.datasource.url=jdbc:oracle:thin:@192.168.50.1:1521/XEPDB1
spring.datasource.username=sarah
spring.datasource.password=gra123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-Client
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.maximum-pool-size=20



# Swagger
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.jdbc=DEBUG
